name: Deploy Next.js to GitHub Pages
on:
  push:
    branches:
      - main  # or your default branch name

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22  # or your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build and Export
        run: |
          npm run build
          touch out/.nojekyll  # Prevents GitHub Pages from bypassing files that begin with an underscore
          cp -r out/* .
          rm -rf out

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
