name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Make sure this matches your default branch name
  # Add workflow dispatch to run manually
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Node version
        run: node --version

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      - name: List directory contents
        run: ls -la

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          echo "Dependencies installed"

      - name: Build project
        run: |
          echo "Starting build..."
          npm run build
          echo "Build completed"

      - name: Prepare files
        run: |
          echo "Preparing files for deployment..."
          touch out/.nojekyll
          cp -r out/* .
          rm -rf out
          echo "Files prepared"

      - name: List files to be deployed
        run: ls -la

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: true

      - name: Deployment status
        run: |
          echo "Deployment completed"
          echo "Check the gh-pages branch for deployed files"
