name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: |
          npm ci

      - name: Build project
        run: |
          npm run build

      - name: Prepare deployment
        run: |
          mkdir -p deployment
          cp -r out/* deployment/
          touch deployment/.nojekyll

      - name: List deployment files
        run: |
          echo "Files to be deployed:"
          ls -la deployment/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deployment
          branch: gh-pages
          clean: true
          clean-exclude: |
            .nojekyll
          force: true

      - name: Verify deployment
        if: success()
        run: |
          git fetch
          git checkout gh-pages || echo "Could not checkout gh-pages"
          echo "Current directory contents:"
          ls -la
